### ISSUE TITLE
overflow error in warp3d2exii

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#16]
Hi, 
I'm trying to expand previous center hole example to notch and shear specimen.
Problem is that when I try to use warp3dexii, overflow error happened.
Can you tell me how can I resolve this problem?

These were the input files.
[input_files.zip](https://github.com/rhdodds/warp3d/files/8139532/input_files.zip)

Error message was like this:
...
...
...
 ./wes0000200_stream  files read: 200
 ./wes0000250_stream  files read: 250
 ./wes0000300_stream  files read: 300
 ./wes0000350_stream  files read: 350
 ./wes0000400_stream  files read: 400
 ./wes0000450_stream  files read: 450
 ./wes0000500_stream  files read: 500
 ...done

Reading integration point results (not implemented)...
 ...done

Completed reading model/results @ wall time:       22.6 (secs)

Writing model and results to ExodusII file: shear.exo
 ...coordinates written
 ...element data written
Traceback (most recent call last):
  File "C:\Users\MML-WORK4\warp3d\warp3d2exii\warp3d2exii", line 202, in <module>
    w.write(model)
  File "C:\Users\MML-WORK4\warp3d\warp3d2exii\writers.py", line 62, in write
    self.write_nodal_variables(model)
  File "C:\Users\MML-WORK4\warp3d\warp3d2exii\writers.py", line 271, in write_nodal_variables
    self.ncdf.sync()
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 404, in flush
    self._write()
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 416, in _write
    self._write_var_array()
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 464, in _write_var_array
    self._write_var_metadata(name)
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 503, in _write_var_metadata
    self._pack_int(vsize)
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 777, in _pack_int
    self.fp.write(array(value, '>i').tobytes())
OverflowError: Python int too large to convert to C long
Exception ignored in: <function ExodusIIWriter.__del__ at 0x0000022AF69DE280>
Traceback (most recent call last):
  File "C:\Users\MML-WORK4\warp3d\warp3d2exii\writers.py", line 325, in __del__
  File "C:\Users\MML-WORK4\warp3d\warp3d2exii\writers.py", line 319, in close
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 404, in flush
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 416, in _write
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 464, in _write_var_array
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 503, in _write_var_metadata
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 777, in _pack_int
OverflowError: Python int too large to convert to C long
Exception ignored in: <function netcdf_file.close at 0x0000022AF68FA670>
Traceback (most recent call last):
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 294, in close
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 404, in flush
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 416, in _write
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 464, in _write_var_array
  File "C:\Users\MML-WORK4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfrar_metadata                                                                                        F8p0\LocalCache\lo8p0\LocalCache\local-packages\Python39\site-packages\scipy\io\netcdf.py", line 777, in _pack_int
OverflowError: Python int too large to convert to C long

**Comment by rhdodds** [comment]
Hi Gyujang,

Several items/issues about your shear model.

1. The errors below seem to be caused by an overflow on your PC.

   As is, your model generates > 11 GB of results files to be read by
   warp3d2exii to make a .exo file for ParaView.

   Suspect your PC does not have enough physical memory and/or swap space.

   warp3d2exii reads all the data files into memory first then writes
   the .exo file.

   Your model, warp3d2exii and ParaView all ran fine on my 
   iMacPro (64 GB physical memory)

2. Suggestions:

    - reduce the number of load steps at which results files are generated.

    - in your warp3d.inp file use this command instead:

        output commands use "get_output.inp" steps 10-1000 by 10  

      only 50 sets (rather than 500 sets) of results files will be 
      generated - about 600 MB rather than 11+ GB

3. Change the get_output.inp file to be the following:

! output for paraview
! output model flat patran convention text file “shear”  <<<<<<<  now commented only needed once in an analysis
 output flat stream displacements
! output flat stream nodal strains              <<<<<<< now commented
! output flat stream nodal reactions            <<<<<<< now commented      
 output flat stream element stresses
 output flat stream element strains
 output flat stream element states

   With all these results in .exo ParaView file, the number of variables for post-
   processing grows quite large.

   Might want to think about what you really want to see.

4. Nice mesh for the shear specimen.

   HOWEVER, I believe you have errors in the boundary conditions.

   Your input:  

       constraints
          plane x=0 symmetry
          plane y=20 symmetry  <<<<< likely wrong
          plane z=1.5 symmetry   <<<<< likely wrong
          plane y=20. v 0.5   

   I think your mean:   plane y = -20 symmetry
      at the bottom of the specimen. this just sets v = 0 on those nodes

   It seems you are modeling the full thickness (3 mm) of the test specimen. Then why
   do you impose symmetry conditions plane z=1.5 symmetry at mid thickness ?  Why not 
   then model 1/2 of the specimen thickness ????

Best,

Bob

**Comment by vivelakorea** [comment]
1.

`
! output model flat patran convention text file “shear”  <<<<<<<  now commented only needed once in an analysis
`

: So do I have to add this command right before 
`
output commands use "get_output.inp" steps 1-1000
`
this command?



2.

`
! output flat stream nodal strains              <<<<<<< now commented
! output flat stream nodal reactions            <<<<<<< now commented
`

About this part.. I have to get history of four values, which are PEEQ, 1st/2nd/3rd principal stress at element that have maximum PEEQ value at failure.
Also, I have to get y direction reaction force history at end point of the specimen(which is contact in real experiment) to compare with experimental results.
So I think I can't comment out reaction part, but I can comment out strains part.
My question is that is PEEQ(c1 value) handled by element state or element stresses?



3.
I am running warp3d in D drive and it has 525GB left, so I can't understand why it is running out of memory... Anyway, is there some method to edit warp3d2exii to get data using buffering or somthing like that, to handle data not as whole?
